import '../models/knowledge.dart';

/// Từ điển khái niệm dùng để trích tri thức từ syllabus FAP.
///
/// Mỗi khái niệm có nhiều cách viết, cả tiếng Anh lẫn tiếng Việt, và đều đi
/// qua đúng bộ chuẩn hoá của [KnowledgeExtractionService] (bỏ dấu, hạ chữ,
/// bỏ số nhiều) trước khi so khớp — nên viết `Linked lists` hay `linked list`
/// ở đây là như nhau.
///
/// Quy tắc khi thêm cách viết:
///
/// - **Tránh từ đơn đa nghĩa.** `stack` là ngăn xếp ở CSD201 nhưng là widget
///   `Stack` ở PRM393; `graph` là đồ thị ở MAD101 nhưng là "đồ thị hàm số" ở
///   MAE101; `sap` bỏ dấu trùng với "sắp" trong mọi syllabus tiếng Việt. Với
///   những từ đó chỉ dùng cụm đủ dài để không thể hiểu sai.
/// - **Cụm dài thắng cụm ngắn.** Bộ so khớp chọn cụm dài nhất tại mỗi vị trí,
///   nên `binary search tree` thuộc về "Cây" chứ không bị tính thành "Tìm
///   kiếm nhị phân", và `widget tree` thuộc về Flutter chứ không thành "Cây".
///   Muốn chặn một nghĩa sai, thêm cụm dài hơn vào khái niệm đúng.
/// - Khái niệm đánh dấu `generic` là kỹ năng chung (làm việc nhóm, dùng công
///   cụ AI...): vẫn hiện ra nhưng không dùng để nối các môn với nhau.
class KnowledgeConcepts {
  KnowledgeConcepts._();

  static const String _p = KnowledgeCategory.programming;
  static const String _d = KnowledgeCategory.dsa;
  static const String _db = KnowledgeCategory.database;
  static const String _w = KnowledgeCategory.webMobile;
  static const String _s = KnowledgeCategory.systems;
  static const String _se = KnowledgeCategory.softwareEngineering;
  static const String _m = KnowledgeCategory.math;
  static const String _x = KnowledgeCategory.society;

  static const List<ConceptDef> all = [
    // ----------------------------------------------------------------
    // LẬP TRÌNH
    // ----------------------------------------------------------------
    ConceptDef('programming', 'Lập trình (nền tảng)', _p, [
      'programming',
      'coding',
      'lập trình',
      'write program',
      'writing program',
      'computer program',
      'develop program',
      'implement program',
    ]),
    ConceptDef('c-language', 'Ngôn ngữ C/C++', _p, [
      'c language',
      'c ~program',
      'c ~programming',
      'c compiler',
      'c library',
      'c/c++',
      'c++',
      'ngôn ngữ c',
      'stdlib.h',
      'string.h',
      'math.h',
      'ctype.h',
      'time.h',
      'c file handling',
    ]),
    ConceptDef('java', 'Java', _p, ['java', 'jdk', 'netbeans', 'eclipse']),
    ConceptDef('csharp-dotnet', 'C# & .NET', _p, [
      'c#',
      '.net',
      'asp.net',
      'asp.net core',
      '.net core',
      'linq',
      'wcf',
      'windows communication foundation',
    ]),
    ConceptDef('dart-flutter', 'Dart & Flutter', _p, [
      'dart',
      'flutter',
      'widget',
      'widget tree',
      'hot reload',
      'stateless',
      'stateful',
      'scaffold',
      'pub.dev',
    ]),
    ConceptDef('javascript', 'JavaScript', _p, [
      'javascript',
      'ajax',
      'typescript',
      'node.js',
      'nodejs',
      'react',
      'jquery',
      'angular',
      'vue.js',
    ]),
    ConceptDef('python', 'Python', _p, [
      'python',
      'jupyter',
      'numpy',
      'pandas',
    ]),
    ConceptDef('oop', 'Hướng đối tượng (OOP)', _p, [
      'object oriented',
      'oop',
      'oo ~programming',
      'hướng đối tượng',
      'class and object',
      'classes and objects',
      'oop concept',
    ]),
    ConceptDef('inheritance', 'Kế thừa, đa hình, đóng gói', _p, [
      'inheritance',
      'polymorphism',
      'encapsulation',
      'abstract class',
    ]),
    ConceptDef('exception', 'Xử lý ngoại lệ', _p, [
      'exception handling',
      'exceptional handling',
      'try catch',
      'xử lý ngoại lệ',
      'error handling',
    ]),
    ConceptDef('collections', 'Collections & Generics', _p, [
      'collections framework',
      'collection framework',
      'java collection',
      'generics',
      'generic class',
      'generics class',
      'generic method',
      'collections & operations',
      'arraylist',
      'hashmap',
    ]),
    ConceptDef('functions', 'Hàm & mô-đun hoá chương trình', _p, [
      'function definition',
      'user defined function',
      'built in function',
      'pass by value',
      'pass by reference',
      'modularity',
      'modularization',
      'modular',
      'function oriented',
      'functional pattern',
      'design modules for a program',
      'hàm con',
    ]),
    ConceptDef('pointer', 'Con trỏ & cấp phát động', _p, [
      'pointer',
      'dynamic allocation',
      'dynamic allocated',
      'con trỏ',
      'reference type',
      'memory allocation',
    ]),
    ConceptDef('variables', 'Biến, kiểu dữ liệu & biểu thức', _p, [
      'variable',
      'data type',
      'expression',
      'operator',
      'casting',
      'constant',
      'struct',
      'kiểu dữ liệu',
      'types & variables',
    ]),
    ConceptDef('control-flow', 'Cấu trúc điều khiển (rẽ nhánh, vòng lặp)', _p, [
      'if else',
      'switch case',
      'loop',
      'conditional',
      'iterative execution',
      'control structure',
      'logic construct',
      'vòng lặp',
      'rẽ nhánh',
    ]),
    ConceptDef('async', 'Bất đồng bộ & stream', _p, [
      'asynchronous',
      'async',
      'streamcontroller',
      'streambuilder',
      'futurebuilder',
      'reactive pattern',
      'future based',
      'bất đồng bộ',
    ]),
    ConceptDef('file-io', 'Tệp & đọc/ghi dữ liệu', _p, [
      'text file',
      'binary file',
      'file handling',
      'file function',
      'accessing file',
      'file type',
      'read and write',
      'formatted output',
      'stream to read',
      'đọc ghi tệp',
    ]),
    ConceptDef('debugging', 'Gỡ lỗi (debug)', _p, [
      'debug',
      'debugging',
      'gỡ lỗi',
      'debugger',
    ]),

    // ----------------------------------------------------------------
    // CẤU TRÚC DỮ LIỆU & GIẢI THUẬT
    // ----------------------------------------------------------------
    ConceptDef('algorithm', 'Thuật toán', _d, [
      'algorithm',
      'thuật toán',
      'giải thuật',
      'pseudocode',
      'pseudo code',
      'flowchart',
      'greedy algorithm',
      'divide and conquer',
      'dynamic programming',
    ]),
    ConceptDef('complexity', 'Độ phức tạp thuật toán', _d, [
      'complexity of algorithm',
      'algorithm complexity',
      'time complexity',
      'space complexity',
      'big o',
      'growth of function',
      'độ phức tạp',
    ]),
    ConceptDef('data-structure', 'Cấu trúc dữ liệu (tổng quan)', _d, [
      'data structure',
      'cấu trúc dữ liệu',
      'abstract data type',
    ]),
    ConceptDef('array', 'Mảng (array)', _d, [
      'array',
      'one dimensional array',
      'two dimensional array',
      'mảng một chiều',
      'mảng hai chiều',
    ]),
    ConceptDef('string', 'Chuỗi ký tự (string)', _d, [
      'string',
      'character array',
      'chuỗi ký tự',
      'array of string',
    ]),
    ConceptDef('linked-list', 'Danh sách liên kết', _d, [
      'linked list',
      'singly linked',
      'doubly linked',
      'circularly linked',
      'list data structure',
      'danh sách liên kết',
    ]),
    ConceptDef('stack-queue', 'Ngăn xếp & hàng đợi', _d, [
      'stack and queue',
      'stacks and queues',
      'queue',
      'priority queue',
      'ngăn xếp',
      'hàng đợi',
    ]),
    ConceptDef('tree', 'Cây (tree, BST, heap)', _d, [
      'tree',
      'binary tree',
      'binary search tree',
      'bst',
      'heap',
      'balanced search tree',
      'avl tree',
      'tree traversal',
      'general tree',
      'decision tree',
      'cây nhị phân',
      'postfix expression',
      'prefix expression',
      'prefix and postfix expression',
      'infix',
    ]),
    ConceptDef('graph', 'Đồ thị (graph)', _d, [
      'graph traversal',
      'directed graph',
      'undirected graph',
      'weighted graph',
      'shortest path',
      'dijkstra',
      'kruskal',
      'bfs',
      'dfs',
      'breadth first',
      'depth first',
      'euler path',
      'hamilton path',
      'graph model',
      'graph terminology',
      'graph isomorphism',
      'spanning tree',
      'minimum spanning tree',
      'representing graph',
      'graph and their application',
      'lý thuyết đồ thị',
      'adjacency matrix',
      'adjacency matrices',
      'incidence matrix',
      'incidence matrices',
    ]),
    ConceptDef('recursion', 'Đệ quy', _d, [
      'recursion',
      'recursive',
      'đệ quy',
      'recurrence relation',
      'recurrence',
    ]),
    ConceptDef('sorting', 'Sắp xếp', _d, [
      'sorting',
      'sort',
      'selection sort',
      'bubble sort',
      'merge sort',
      'quick sort',
      'insertion sort',
      'radix sort',
      'bucket sort',
      'heap sort',
      'sắp xếp',
    ]),
    ConceptDef('searching', 'Tìm kiếm', _d, [
      'searching',
      'binary search',
      'linear search',
      'search algorithm',
      'sequential search',
    ]),
    ConceptDef('hashing', 'Băm (hashing)', _d, [
      'hash',
      'hashing',
      'hash table',
      'hash function',
      'rehashing',
      'load factor',
    ]),
    ConceptDef('text-processing', 'Xử lý văn bản & nén', _d, [
      'huffman',
      'huffman coding',
      'lzw',
      'run length',
      'text compression',
      'compression',
      'text processing',
      'pattern matching',
    ]),

    // ----------------------------------------------------------------
    // CƠ SỞ DỮ LIỆU
    // ----------------------------------------------------------------
    ConceptDef('database', 'Cơ sở dữ liệu', _db, [
      'database',
      'dbms',
      'cơ sở dữ liệu',
      'csdl',
      'relational database',
      'local db',
      'db table',
      'database design',
      'database system',
    ]),
    ConceptDef('sql', 'SQL & truy vấn', _db, [
      'sql',
      'query',
      'ddl',
      'dml',
      'nested query',
      'aggregation query',
      'sql server',
      'mysql',
      'postgresql',
      'crud',
      'truy vấn',
      'data definition language',
      'data manipulation language',
    ]),
    ConceptDef('relational-model', 'Mô hình quan hệ & chuẩn hoá', _db, [
      'relational model',
      'relational algebra',
      'algebraic query',
      'normalization',
      'normal form',
      'functional dependency',
      'bcnf',
      '3nf',
      'chuẩn hoá',
      'primary key',
      'foreign key',
      'key and foreign key',
      'constraints on attribute',
      'table and constraint',
      'relational database schema',
    ]),
    ConceptDef('erd', 'Mô hình thực thể – liên kết (ERD)', _db, [
      'er diagram',
      'erd',
      'entity relationship',
      'entity set',
      'weak entity',
      'conceptual modeling',
      'data modeling',
      'data model',
    ]),
    ConceptDef('db-programming', 'Stored procedure, trigger & cursor', _db, [
      'stored procedure',
      'trigger',
      'cursor',
      'pl/sql',
      't-sql',
      'plsql',
      'database trigger',
    ]),
    ConceptDef('transaction', 'Giao tác (transaction)', _db, [
      'transaction',
      'acid',
      'concurrency control',
      'giao tác',
    ]),
    ConceptDef('index', 'Chỉ mục & tối ưu truy vấn', _db, [
      'index',
      'indexing',
      'query optimization',
      'tối ưu truy vấn',
    ]),
    ConceptDef('db-access', 'Truy cập CSDL từ ứng dụng (JDBC, ORM)', _db, [
      'jdbc',
      'odbc',
      'ado.net',
      'jpa',
      'hibernate',
      'entity framework',
      'orm',
      'interacting with database',
      'connect to database',
      'odata',
    ]),

    // ----------------------------------------------------------------
    // WEB & DI ĐỘNG
    // ----------------------------------------------------------------
    ConceptDef('html-css', 'HTML, CSS & thiết kế web', _w, [
      'html',
      'css',
      'bootstrap',
      'responsive',
      'web design',
      'web page',
      'webpage',
      'html text',
    ]),
    ConceptDef('http', 'HTTP, request/response, session & cookie', _w, [
      'http',
      'https',
      'request and response',
      'request & response',
      'query string',
      'cookie',
      'session and cookie',
      'web protocol',
      'form submission',
      'form submition',
      'session scope',
      'sessionscope',
      'http request',
    ]),
    ConceptDef('rest-api', 'RESTful API & web service', _w, [
      'restful',
      'rest api',
      'web api',
      'web service',
      'webservice',
      'api',
      'json',
      'xml',
      'grpc',
      'soap',
      'content negotiation',
      'media formatter',
      'restful service',
      'json parsing',
    ]),
    ConceptDef('servlet-jsp', 'Servlet & JSP', _w, [
      'servlet',
      'jsp',
      'expression language',
      'jstl',
      'tomcat',
      'java web',
      'el function',
    ]),
    ConceptDef('mvc', 'Mô hình MVC', _w, [
      'mvc',
      'model view controller',
      'mvc architecture',
      'mvc pattern',
    ]),
    ConceptDef('web-app', 'Ứng dụng web (front-end/back-end)', _w, [
      'web application',
      'web app',
      'web development',
      'website',
      'front end',
      'back end',
      'frontend',
      'backend',
      'full stack',
      'web server',
      'client side',
      'server side',
      'web front end',
    ]),
    ConceptDef('mobile-app', 'Ứng dụng di động', _w, [
      'mobile',
      'android',
      'ios',
      'di động',
      'mobile application',
      'deep linking',
    ]),
    ConceptDef('ui-ux', 'Giao diện & trải nghiệm (UI/UX)', _w, [
      'ui/ux',
      'user interface',
      'user experience',
      'ux',
      'ui',
      'usability',
      'wireframe',
      'layout',
      'theming',
      'interaction design',
      'giao diện',
      'user interaction',
      'responsive ui',
    ]),
    ConceptDef('navigation-state', 'Điều hướng & quản lý trạng thái', _w, [
      'state management',
      'navigation',
      'navigator',
      'named route',
      'guarded route',
      'session state',
    ]),
    ConceptDef('local-storage', 'Lưu trữ cục bộ', _w, [
      'sqlite',
      'shared preferences',
      'sharedpreferences',
      'hive',
      'local storage',
      'store data locally',
      'token persistence',
    ]),
    ConceptDef('auth', 'Xác thực & phân quyền', _w, [
      'authentication',
      'authorization',
      'login',
      'logout',
      'jwt',
      'token',
      'auth',
      'password',
      'đăng nhập',
      'mock auth',
    ]),
    ConceptDef('notification', 'Thông báo đẩy', _w, [
      'push notification',
      'notification',
      'local notification',
    ]),
    ConceptDef('deployment', 'Triển khai & phát hành', _w, [
      'deploy',
      'deployment',
      'release build',
      'build & release',
      'packaging',
      'hosting',
      'devops',
      'ci/cd',
      'release config',
    ]),
    ConceptDef('version-control', 'Quản lý phiên bản (Git)', _w, [
      'git',
      'github',
      'gitlab',
      'version control',
      'source control',
    ]),

    // ----------------------------------------------------------------
    // HỆ THỐNG & MẠNG
    // ----------------------------------------------------------------
    ConceptDef('computer-architecture', 'Kiến trúc & tổ chức máy tính', _s, [
      'computer architecture',
      'computer organization',
      'computer organisation',
      'von neumann',
      'stored program',
      'bus',
      'computer hardware',
      'hardware organization',
      'digital computer',
      'kiến trúc máy tính',
      'subsystems of a computer',
      'computer function and interconnection',
    ]),
    ConceptDef('cpu', 'Bộ vi xử lý (CPU, vi điều khiển)', _s, [
      'cpu',
      'processor',
      'microprocessor',
      'microcontroller',
      'register',
      'pipelining',
      'superscalar',
      'multicore',
      'instruction level parallelism',
      'reduced instruction set',
      'risc',
      'atmega328',
      'atmega328p',
      'parallel processing',
    ]),
    ConceptDef('instruction-set', 'Tập lệnh & hợp ngữ', _s, [
      'instruction set',
      'machine instruction',
      'machine code',
      'machine language',
      'assembly',
      'assembly language',
      'addressing mode',
      'hợp ngữ',
    ]),
    ConceptDef('memory', 'Bộ nhớ & quản lý bộ nhớ', _s, [
      'memory',
      'cache memory',
      'virtual memory',
      'memory management',
      'paging',
      'page replacement',
      'address space',
      'address translation',
      'bộ nhớ',
      'internal memory',
      'external memory',
      'memory operation',
    ]),
    ConceptDef('operating-system', 'Hệ điều hành', _s, [
      'operating system',
      'os',
      'kernel',
      'system call',
      'hệ điều hành',
      'operating system support',
    ]),
    ConceptDef('linux-shell', 'Linux & dòng lệnh', _s, [
      'linux',
      'shell',
      'command line',
      'bash',
      'terminal',
      'unix',
      'shell command',
    ]),
    ConceptDef('process-thread', 'Tiến trình, luồng & đồng bộ', _s, [
      'process management',
      'processes and threads',
      'thread',
      'multithreading',
      'cpu scheduling',
      'process scheduling',
      'interprocess communication',
      'ipc',
      'deadlock',
      'synchronization',
      'race condition',
      'semaphore',
      'multi tasking',
      'multitasking',
    ]),
    ConceptDef('file-system', 'Hệ thống tệp & lưu trữ', _s, [
      'file system',
      'file structure',
      'disk',
      'storage device',
      'file system implementation',
    ]),
    ConceptDef('io-system', 'Vào/ra (I/O) & ngắt', _s, [
      'input output',
      'input/output',
      'i/o',
      'in/out',
      'interrupt',
      'interrupt handling',
      'i/o device',
      'io device',
      'peripheral',
      'i/o system',
    ]),
    ConceptDef('number-representation', 'Hệ cơ số & biểu diễn dữ liệu', _s, [
      'binary',
      'binary number',
      'hexadecimal',
      'octal',
      'decimal',
      'number system',
      'base b expansion',
      'base conversion',
      'floating point',
      'bit pattern',
      'bit operator',
      'bitwise',
      "two's complement",
      'số nhị phân',
    ]),
    ConceptDef('digital-logic', 'Mạch số & điện tử', _s, [
      'boolean algebra',
      'digital logic',
      'logic gate',
      'digital circuit',
      'combinational circuit',
      'flip flop',
      'đại số boole',
      'electrical circuit',
      'electronics',
      'electronic component',
      'electronics component',
      'electrical circuits and electronics',
    ]),
    ConceptDef('networking', 'Mạng máy tính & giao thức', _s, [
      'network',
      'networking',
      'netwoking',
      'computer network',
      'protocol',
      'osi',
      'tcp',
      'udp',
      'topology',
      'ethernet',
      'mạng máy tính',
      'internet connection',
      'packet',
      'data link',
      'transport layer',
      'network layer',
      'physical layer',
      'application layer',
      'port number',
      'layered protocol',
    ]),
    ConceptDef('ip-routing', 'Địa chỉ IP, định tuyến & chuyển mạch', _s, [
      'ip address',
      'ip addressing',
      'ipv4',
      'ipv6',
      'subnet',
      'subnetting',
      'router',
      'routing table',
      'switching',
      'mac address',
      'arp',
      'icmp',
      'ping',
      'traceroute',
      'vlan',
      'router configuration',
    ]),
    ConceptDef('iot', 'IoT & hệ nhúng', _s, [
      'iot',
      'internet of things',
      'arduino',
      'sensor',
      'actuator',
      'embedded system',
      'raspberry pi',
      'arduino uno',
      'microcontroller kit',
    ]),
    ConceptDef('security', 'Bảo mật & an toàn thông tin', _s, [
      'security',
      'secure',
      'securing',
      'encryption',
      'cryptography',
      'cryptology',
      'attack',
      'hardening',
      'vulnerability',
      'bảo mật',
      'an toàn thông tin',
      'malware',
      'firewall',
      'web security',
    ]),
    ConceptDef('cloud', 'Điện toán đám mây', _s, [
      'cloud',
      'aws',
      'azure',
      'docker',
      'container',
      'kubernetes',
    ]),

    // ----------------------------------------------------------------
    // KỸ NGHỆ PHẦN MỀM
    // ----------------------------------------------------------------
    ConceptDef('sdlc', 'Quy trình phát triển phần mềm (SDLC)', _se, [
      'sdlc',
      'software development life cycle',
      'software life cycle',
      'software lifecycle',
      'software development process',
      'development methodology',
      'software process',
      'waterfall',
      'software development method',
      'production process',
      'steps to develop a software',
      'software development practice',
    ]),
    ConceptDef('requirements', 'Kỹ nghệ yêu cầu', _se, [
      'software requirement',
      'requirements engineering',
      'requirement engineering',
      'requirement enginneering',
      'requirement development',
      'requirement inception',
      'requirement analysis',
      'requirements analysis',
      'requirement management',
      'requirements management',
      'data requirement',
      'project requirement',
      'functional requirement',
      'non functional requirement',
      'system requirement',
      'elicitation',
      'specification',
      'user requirement',
      'business requirement',
      'user need',
      'user story',
      'business analyst',
      'validating the requirement',
      'documenting the requirement',
      'writing excellent requirement',
      'requirements and use case',
    ]),
    ConceptDef('uml', 'UML, use case & mô hình hoá', _se, [
      'use case',
      'uml',
      'class diagram',
      'sequence diagram',
      'activity diagram',
      'state diagram',
      'statechart',
      'object interaction diagram',
      'domain model',
      'usage model',
      'plantuml',
      'comet',
      'static modeling',
      'dynamic interaction modeling',
      'analysis model',
      'use case modeling',
    ]),
    ConceptDef('architecture', 'Kiến trúc & thiết kế phần mềm', _se, [
      'software architecture',
      'software design',
      'architectural design',
      'system design',
      'design model',
      'client/server',
      'client server',
      'service oriented',
      'soa',
      'microservice',
      'component based',
      'layered architecture',
      'design system module',
      'software architectures',
    ]),
    ConceptDef('design-patterns', 'Design pattern', _se, [
      'design pattern',
      'repository pattern',
      'singleton',
      'factory pattern',
      'observer pattern',
      'creational',
      'structural pattern',
      'behavioral pattern',
      'mvvm',
      'repository & service layer',
    ]),
    ConceptDef('testing', 'Kiểm thử phần mềm', _se, [
      'testing',
      'software testing',
      'test case',
      'unit test',
      'integration test',
      'system test',
      'acceptance test',
      'test plan',
      'test design',
      'black box',
      'white box',
      'test automation',
      'automation testing',
      'test coverage',
      'kiểm thử',
      'bug report',
      'bug logging',
      'istqb',
      'widget test',
      'user acceptance',
      'test level',
      'test type',
      'static testing',
      'dynamic testing',
      'test management',
    ]),
    ConceptDef('agile', 'Agile, Scrum & Lean', _se, [
      'agile',
      'scrum',
      'sprint',
      'kanban',
      'lean',
      'retrospective',
      'agile practice',
      'agile testing',
    ]),
    ConceptDef('project-management', 'Quản lý dự án', _se, [
      'project management',
      'project plan',
      'project planning',
      'project scope',
      'work breakdown',
      'wbs',
      'project budget',
      'project resource',
      'gantt',
      'milestone',
      'quản lý dự án',
      'phase planning',
      'communications management plan',
    ]),
    ConceptDef('risk', 'Quản lý rủi ro', _se, [
      'risk',
      'risk management',
      'rủi ro',
      'risk reduction',
    ]),
    ConceptDef('prototyping', 'Làm bản mẫu (prototype)', _se, [
      'prototype',
      'prototyping',
      'mockup',
      'bản mẫu',
      'fidelity',
    ]),
    ConceptDef('quality', 'Chất lượng & bảo trì phần mềm', _se, [
      'software quality',
      'quality assurance',
      'code review',
      'high quality software',
      'quality improvement',
      'configuration management',
      'maintenance',
      'maintenance testing',
      'code smell',
    ]),
    ConceptDef('erp-sap', 'ERP & SAP', _se, [
      'erp',
      'sap system',
      'sap project',
      'sap module',
      'enterprise structure',
      'enterprise resource planning',
      'business processes for involved modules in sap',
    ]),

    // ----------------------------------------------------------------
    // TOÁN & DỮ LIỆU
    // ----------------------------------------------------------------
    ConceptDef('logic', 'Logic mệnh đề & vị từ', _m, [
      'propositional logic',
      'proposition',
      'predicate',
      'quantifier',
      'logical expression',
      'rules of inference',
      'inference',
      'truth value',
      'truth table',
      'logic mệnh đề',
      'logical equivalence',
      'propositional equivalence',
      'predicate logic',
    ]),
    ConceptDef('set-function', 'Tập hợp, ánh xạ & dãy', _m, [
      'set theory',
      'set operation',
      'power set',
      'cartesian product',
      'sequences and summation',
      'summation',
      'introduction to set',
      'sets, functions and sequences',
    ]),
    ConceptDef('induction', 'Quy nạp & chứng minh', _m, [
      'induction',
      'mathematical induction',
      'strong induction',
      'proof',
      'prove',
      'quy nạp',
      'structural induction',
    ]),
    ConceptDef('counting', 'Tổ hợp & phép đếm', _m, [
      'counting',
      'combinatorics',
      'permutation',
      'combination',
      'pigeonhole',
      'counting principle',
      'counting problem',
    ]),
    ConceptDef('number-theory', 'Số học & đồng dư', _m, [
      'modular arithmetic',
      'congruence',
      'integer division',
      'prime',
      'greatest common divisor',
      'gcd',
      'integers and division',
      'number theory',
      'pseudorandom',
    ]),
    ConceptDef('calculus', 'Giải tích (giới hạn, đạo hàm, tích phân)', _m, [
      'calculus',
      'derivative',
      'integral',
      'limit of a function',
      'differentiation',
      'riemann sum',
      'giải tích',
      'đạo hàm',
      'tích phân',
      'single variable',
      'linear approximation',
      'implicit differentiation',
    ]),
    ConceptDef('linear-algebra', 'Đại số tuyến tính & ma trận', _m, [
      'linear algebra',
      'matrix',
      'matrices',
      'determinant',
      'eigenvalue',
      'diagonalization',
      'vector space',
      'subspace',
      'linear transformation',
      'gaussian elimination',
      'system of linear equation',
      'dot product',
      'vector',
      'ma trận',
      'linear system of equation',
    ]),
    ConceptDef('statistics', 'Xác suất & thống kê', _m, [
      'probability',
      'statistics',
      'statistical',
      'random variable',
      'probability distribution',
      'mean and variance',
      'variance',
      'sampling',
      'sample space',
      'confidence interval',
      'hypothesis testing',
      'hypothesis test',
      'central limit',
      'regression',
      'correlation',
      'xác suất',
      'thống kê',
      'histogram',
      'descriptive statistic',
      'sampling distribution',
      'linear regression',
      'statistical inference',
      'conditional probability',
      'testing hypotheses',
      'testing hypothesis',
      'bayes theorem',
    ]),
    ConceptDef('data-analysis', 'Phân tích dữ liệu & báo cáo', _m, [
      'data analysis',
      'analytics',
      'data visualization',
      'dashboard',
      'data extraction',
      'data preparation',
      'analyze data',
      'phân tích dữ liệu',
    ]),
    ConceptDef('ai-ml', 'Trí tuệ nhân tạo & học máy', _m, [
      'machine learning',
      'deep learning',
      'neural network',
      'artificial intelligence',
      'trí tuệ nhân tạo',
      'học máy',
      'data science',
      'data driven technology',
      'data driven technologies',
    ]),

    // ----------------------------------------------------------------
    // KỸ NĂNG & XÃ HỘI
    // ----------------------------------------------------------------
    ConceptDef('ai-tools', 'Dùng công cụ AI hỗ trợ học tập', _x, [
      'ai tool',
      'using ai',
      'use ai',
      'ai assisted',
      'ai assistance',
      'ai support',
      'ai supported',
      'ai enhanced',
      'ai driven',
      'ai aided',
      'chatgpt',
      'copilot',
      'ai agent',
      'responsible ai',
      'ứng dụng ai',
      'sử dụng ai',
      'ai augmented',
      'chat ai',
      'generative ai',
      'use chatgpt',
      'using ai in',
      'digital tool',
      'digital literacy',
      'ai responsibly',
      'ai application',
      'ai enabled',
    ], generic: true),
    ConceptDef('teamwork', 'Làm việc nhóm', _x, [
      'teamwork',
      'team work',
      'working in group',
      'work in team',
      'group work',
      'in group working',
      'làm việc nhóm',
      'hoạt động nhóm',
      'team',
      'collaborate',
      'collaboration',
      'group discussion',
    ], generic: true),
    ConceptDef('communication', 'Giao tiếp & thuyết trình', _x, [
      'communication skill',
      'communicate effectively',
      'communicating',
      'presentation',
      'thuyết trình',
      'giao tiếp',
      'persuasive',
      'verbal',
      'nonverbal',
      'public speaking',
      'presentation skill',
    ], generic: true),
    ConceptDef(
      'critical-thinking',
      'Tư duy phản biện & giải quyết vấn đề',
      _x,
      [
        'critical thinking',
        'problem solving',
        'creative thinking',
        'creativity',
        'tư duy phản biện',
        'giải quyết vấn đề',
        'sáng tạo',
        'problem-solving skill',
      ],
      generic: true,
    ),
    ConceptDef('self-learning', 'Tự học & học tập suốt đời', _x, [
      'self study',
      'self learning',
      'self directed',
      'lifelong learning',
      'tự học',
      'học tập suốt đời',
      'study skill',
      'self-learning',
    ], generic: true),
    ConceptDef('research', 'Phương pháp nghiên cứu', _x, [
      'research method',
      'research',
      'research proposal',
      'literature review',
      'qualitative',
      'quantitative',
      'nghiên cứu',
      'phương pháp nghiên cứu',
      'survey',
      'interview',
    ]),
    ConceptDef('academic-writing', 'Viết học thuật & báo cáo', _x, [
      'academic writing',
      'essay',
      'report',
      'technical report',
      'business writing',
      'citation',
      'citing source',
      'plagiarism',
      'mla',
      'thesis statement',
      'soạn thảo',
      'academic reading',
      'written report',
    ]),
    ConceptDef('ethics', 'Đạo đức nghề nghiệp', _x, [
      'ethic',
      'ethical',
      'professional ethic',
      'đạo đức',
      'ethical issue',
    ]),
    ConceptDef('entrepreneurship', 'Khởi nghiệp & kinh doanh', _x, [
      'startup',
      'start up',
      'entrepreneur',
      'entrepreneurship',
      'business model',
      'pitch deck',
      'market research',
      'marketing',
      'sale',
      'customer acquisition',
      'khởi nghiệp',
      'kinh doanh',
    ]),
    ConceptDef('leadership', 'Lãnh đạo & điều phối nhóm', _x, [
      'leadership theory',
      'leadership effectiveness',
      'powerful leader',
      'effective leader',
      'leadership skill',
      'conflict',
      'business meeting',
    ]),
    ConceptDef('japanese', 'Tiếng Nhật', _x, [
      'japanese',
      'tiếng nhật',
      'chữ hán',
      'kanji',
      'hiragana',
      'katakana',
      'người nhật',
      'nhật bản',
    ]),
    ConceptDef('english', 'Tiếng Anh', _x, [
      'english',
      'tiếng anh',
      'ielts',
      'toefl',
    ]),
    ConceptDef('political-theory', 'Lý luận chính trị', _x, [
      'mác lênin',
      'marx',
      'marxism',
      'leninism',
      'marxist',
      'chủ nghĩa xã hội',
      'xã hội chủ nghĩa',
      'tư tưởng hồ chí minh',
      'hồ chí minh',
      'đảng cộng sản',
      'duy vật',
      'biện chứng',
      'kinh tế chính trị',
      'triết học',
      'giai cấp',
      'cách mạng',
      'marxism-leninism',
      'communist party',
      "party's leadership",
      'leadership of the party',
    ]),
    ConceptDef('military', 'Quốc phòng & an ninh', _x, [
      'national security',
      'national defense',
      'national defence',
      'military',
      'quốc phòng',
      'giáo dục quốc phòng',
    ]),
    ConceptDef('physical', 'Thể chất & võ thuật', _x, [
      'vovinam',
      'võ đạo',
      'thể chất',
      'thể dục',
      'physical education',
      'martial art',
      'sức khỏe',
      'sức khoẻ',
    ]),
    ConceptDef('music', 'Âm nhạc truyền thống', _x, [
      'traditional music',
      'âm nhạc',
      'nhạc cụ',
      'trống dân tộc',
      'musical instrument',
      'traditional drum',
    ]),
  ];

  static final Map<String, ConceptDef> byId = {for (final c in all) c.id: c};
}
